name: Test

on: 
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_workout_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Get the code
        uses: actions/checkout@v4

      # Server
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'

      - name: Install Server dependencies
        run: |
          cd server/app
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run Server tests
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_workout_db
        run: |
          cd server/app
          python -m pytest tests/ -v

      # Client
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Client Dependencies
        run: |
          cd client
          npm ci

      - name: Run Client Tests
        run: |
          cd client
          npm test
